name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "benhowes/test-img"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deploy against'
        type: environment
        required: true
      version:
        description: 'Semver version to deploy'
        required: true

jobs:

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{ secrets.APTIBLE_ROBOT_USERNAME }}
          password: ${{ secrets.APTIBLE_ROBOOT_PASSWORD }}
          app: ${{ secrets.APTIBLE_APP }}
          environment: ${{ secrets.APTIBLE_ENVIRONMENT }}
          docker_img: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
          private_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          private_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
