name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "benhowes/test-img"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deploy against'
        type: environment
        required: true
      version:
        description: 'Semver version to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{ secrets.APTIBLE_ROBOT_USERNAME }}
          password: ${{ secrets.APTIBLE_ROBOOT_PASSWORD }}
          app: ${{ secrets.APTIBLE_APP }}
          environment: ${{ secrets.APTIBLE_ENVIRONMENT }}
          docker_img: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
          private_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          private_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
